# Generated by Django 3.1.1 on 2020-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_child_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='fees',
            field=models.BooleanField(default=False),
        ),
    ]
